# Generated by Django 4.1.5 on 2023-01-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
    ]
