# Generated by Django 4.1.5 on 2023-01-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_user_delete_profile_alter_item_owner_alter_post_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(to='marketplace.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Painting', 'Painting'), ('Ceramics', 'Ceramics'), ('Knitting and Crocheting', 'Knitting and Crocheting'), ('Illustration and Drawing', 'Illustration and Drawing'), ('Embroidery', 'Embroidery'), ('Sculpture', 'Sculpture')], max_length=200),
        ),
    ]
