# Generated by Django 4.1.5 on 2023-01-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='categories',
            new_name='category',
        ),
    ]
