# Generated by Django 4.1.5 on 2023-01-27 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_rename_categories_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='categories',
        ),
    ]
