# Generated by Django 4.1.5 on 2023-01-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_rename_categories_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Painting', 'Painting'), ('Ceramics', 'Ceramics'), ('Yarn and Needlework', 'Yarn and Needlework'), ('Illustration and Drawing', 'Illustration and Drawing'), ('Sculpture', 'Sculpture'), ('Printmaking', 'Printmaking'), ('Photography', 'Photography'), ('Calligraphy', 'Calligraphy'), ('Textiles', 'Textiles')], max_length=200),
        ),
    ]
