# Generated by Django 4.1.5 on 2023-01-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(related_name='items', to='marketplace.category'),
        ),
    ]
