# Generated by Django 4.1.5 on 2023-01-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_remove_item_postid_post_itemid_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='itemId',
        ),
        migrations.AddField(
            model_name='post',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='posts', to='marketplace.item'),
        ),
    ]
