# Generated by Django 4.1.5 on 2023-01-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_alter_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='post_items', to='marketplace.item'),
        ),
    ]
