# Generated by Django 4.1.5 on 2023-02-01 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_postimage_remove_post_items_post_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='owner',
        ),
    ]
