# Generated by Django 4.1.5 on 2023-02-02 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_remove_postimage_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
    ]
