# Generated by Django 4.1.5 on 2023-02-02 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_rename_category_post_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='category',
        ),
    ]
